config:
  server:
    student-key: Hello, from Config Server

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:dbtest"
    username: sa
    password:

info:
  app:
    name: log-service
    description: log service
    version: v1.0