spring:
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:dbtest"
    username: sa
    password:

info:
  app:
    name: student-service
    description: student service
    version: v1.0